apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-eks
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-aws-eks
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.7.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-helm
      version: "v0.16.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.10.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v0.47.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v0.47.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v0.47.0"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      # renovate: datasource=github-releases depName=upbound/function-patch-and-transform
      version: "v0.2.1"
