apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-eks
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-aws-eks
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      AWS EKS Configuration is reusable Configuration designed to be primarily used in higher level Configurations.
    meta.crossplane.io/readme: |
      This configuration bundles an Upbound Cloud extension and an API definition. This API allows control planes to provision AWS EKS clusters, composed using cloud service primitives from the Upbound Official Providers

spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.11.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-helm
      version: "v0.17.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.11.4"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v1.1.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v1.1.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: "v1.1.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.3.0"
