apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: eks.aws.platform.upbound.io
spec:
  group: aws.platform.upbound.io
  names:
    categories:
    - crossplane
    kind: EKS
    plural: eks
  scope: Namespaced
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: EKS is the Schema for the EKS API.
        properties:
          spec:
            description: EKSSpec defines the desired state of EKS.
            properties:
              parameters:
                type: object
                description: EKS configuration parameters.
                properties:
                  id:
                    type: string
                    description: ID of this Cluster that other objects will use to refer to it.
                  region:
                    type: string
                    description: Region is the region you'd like your resource to be created in.
                  accessConfig:
                    type: object
                    properties:
                      bootstrapClusterCreatorAdminPermissions:
                        type: boolean
                        description: Whether or not to bootstrap the access config values to the cluster. Default is false.
                      authenticationMode:
                        type: string
                        enum:
                        - CONFIG_MAP
                        - API
                        - API_AND_CONFIG_MAP
                    default:
                      bootstrapClusterCreatorAdminPermissions: true
                      authenticationMode: CONFIG_MAP
                  iam:
                    type: object
                    description: IAM configuration to connect as ClusterAdmin.
                    properties:
                      principalArn:
                        description: The principal ARN to connect as ClusterAdmin.
                        type: string
                  managementPolicies:
                      description: ManagementPolicies for AWS EC2 resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use ["Create", "Observe", "Update", "LateInitialize"].
                      type: array
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                          - LateInitialize
                        default: "*"
                  providerConfigName:
                    description: Crossplane ProviderConfig to use for provisioning this resources
                    type: string
                    default: default
                  version:
                    description: Kubernetes version
                    type: string
                    enum:
                    - "1.34"                      
                    - "1.33"
                    - "1.32"
                    - "1.31"
                    default: "1.34"
                  nodes:
                    type: object
                    description: EKS node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      instanceType:
                        type: string
                        description: instance types associated with the Node Group.
                        default: t3.small
                    required:
                    - count
                    - instanceType
                required:
                - id
                - region
                - providerConfigName
                - nodes
            required:
            - parameters
            type: object
          status:
              description: A Status represents the observed state
              properties:
                eks:
                  description: Freeform field containing status information for eks
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
        required:
        - spec
        type: object
    served: true
