apiVersion: aws.platform.upbound.io/v1alpha1
kind: XEKS
metadata:
  name: configuration-aws-eks-kcl
  annotations:
    render.crossplane.io/composition-path: apis/kcl/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  compositionSelector:
    matchLabels:
      function: kcl
  parameters:
    id: configuration-aws-eks-kcl
    region: us-west-2
    version: "1.27"
    nodes:
      count: 1
      instanceType: t3.small
  writeConnectionSecretToRef:
    name: configuration-aws-eks-kcl-kubeconfig
    namespace: upbound-system
