apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xeks.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: XEKS
  mode: Pipeline
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
      - sequence:
        - kubernetesCluster
        - kubernetesClusterAuth
        - vpc-cni-addon
        - nodeGroupPublic
      - sequence:
        - nodeGroupPublic
        - aws-ebs-csi-driver-addon
      - sequence:
        - nodeGroupPublic
        - eks-pod-identity-agent-addon
    step: sequence-creation
  - functionRef:
      name: upbound-configuration-aws-eksxeks
    step: xeks
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
