apiVersion: aws.platform.upbound.io/v1alpha1
kind: EKS
metadata:
  name: configuration-aws-eks
  namespace: default
spec:
  parameters:
    id: configuration-aws-eks
    region: us-west-2
    accessConfig:
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    nodes:
      count: 1
      instanceType: t3.small
